import type {Metadata} from "next";
import {Geist, Geist_Mono, Oswald} from "next/font/google";
import "./globals.css";
import {LanguageProvider} from "@/components/LanguageProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const oswald = Oswald({
    variable: "--font-oswald",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} antialiased bg-black`}
        >
        <LanguageProvider>{children}</LanguageProvider>
        </body>
        </html>
    );
}